# Configuration file for Travis continuous integration.
# See https://travis-ci.org/apache/calcite
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
language: java
matrix:
  fast_finish: true
  include:
    - env: IMAGE=maven:3-jdk-11
    - env: IMAGE=maven:3-jdk-10
    - env: IMAGE=maven:3-jdk-9
    - env: IMAGE=maven:3-jdk-8
branches:
  only:
    - master
    - new-master
    - javadoc
    - /^branch-.*$/
    - /^[0-9]+-.*$/
env:
  global:
  - DOCKERRUN="docker run -it --rm -v $PWD:/src -v $HOME/.m2:/root/.m2 -w /src"  
  - secure: "DqoCj2vHVC31Wr+hjTj21q38sPO/DPcYYnR1chPRXvOLzz4a9muf+89PZc3seZnbiGRyMcGhSHlm174l33rYicdJdWBhoqSjfmuYu9rFq9n3ev1Xs/sT7uC78E9ehnoXYciE5KxeefitRrA0KJ6rVIe/v9YY3HeXiQNryzXStPBbWB3MCfNmZCixr+RhRd7JadmGnC1Dlcjeq82pIgJ65yAiJ1gml5Lf0fXfZoAOWIgl4cutMCiZ0t18eaL5ReeFTCkfKahaSTOHayHGos+HzKV2fcGcEFJWsbVroDoyBezP3CIgnh5cjGO63OBQR6wpjuconziVzpBFOEw7CBk1iN+cyow9NLUyZtEUmxDnLUDBexg9xqmJA67vkY4d2MFGduZCPE1rDxR4mRHC9cm83FAfmfUIBph0BL5yMSUfGz9cm0ciCNHmjCrkMkkKFymHClCmO8oKQpAOgEK4xJbfMi7bmKKqmofnqZXBQDB+bGQi1XThdKG8HMxEOqY+Sohsmo03DMOQY4dRfSyd9aXgcS551ijiGaPZTLunqcmVlXiIKsSwtzI7YCQLfiXmSGiSuGSlTasb2dTlAzFf2al0zAjCf5iOGubRQl6zFBuZR7Ju059tXOAm4aDvI1nVayy9RSFb76D51M76/krI+A9jxiEZxz84WibaUZMrBbrPKJs="
services:
  - docker
before_install:
  - docker pull $IMAGE
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
  # Print the Maven version, skip tests and javadoc
  - $DOCKERRUN $IMAGE mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit -B -V
script:
  # Print surefire output to the console instead of files
  - unset _JAVA_OPTIONS
  - $DOCKERRUN $IMAGE mvn -Dsurefire.useFile=false -Dsurefire.parallel= -Djavax.net.ssl.trustStorePassword=changeit test
git:
  depth: 10000
sudo: required
cache:
  directories:
    - $HOME/.m2
addons:
  coverity_scan:
    project:
      name: "snuyanzin/calcite"
      description: "<Your project description here>"
    notification_email: snuyanzin@gmail.com    
    build_command: "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djavax.net.ssl.trustStorePassword=changeit -B -V"
    branch_pattern: coverity_scan    
# End .travis.yml
